### PR TITLE
Feat/1 load remote model

### PR DESCRIPTION
**Pull request by arunge**
#1

- the content of the help is now saved into a help.html file when downloading a model object
- load predefined model
- UI (1) and backend to load a predefined model object
  - there is a new folder "predefinedModels" under inst/app/ that contains zip files of (predefined) models that can be loaded
    - this [folder](https://github.com/Pandora-IsoMemo/osteo-bior/tree/feat/1_loadRemoteModel/inst/app/predefinedModels) can be used to make particular models available to the user
  - this is not exactly what was requested (https://github.com/Pandora-IsoMemo/osteo-bior/issues/1#issue-1138371475)
    - advantage: that the predefined models will be available also offline
    - disadvantage: the size of the app increases the more models are predefined -> we could also create a seperate (public) repository to store the remote model objects
  - replace load of RData file into global environment with readRDS as local object
  - use a path variable to predefined models
- moved the buttons from below to left of the inputs (2, 3) to save some space
- [x] "Summary" tab is not updated when uploading a model -> check/fix this

image

### CODE REVIEW

**Comment by arunge** [comment]
@wahani I have created a new folder in the package: `"./predefinedModels"` for saving predefined models that can be uploaded. We talked about it last week. I did the same for bpred in order to remove the dependency to the private repository (https://github.com/Pandora-IsoMemo/bpred/pull/3).
Could you check the file structure and code here?

**Comment by wahani** [comment]
@arunge 

- How large are these model objects?
- If size is acceptable, can you please upload a model object so we can test that this works?

**Comment by wahani** [comment]
>     How large are these model objects?
>     If size is acceptable, can you please upload a model object so we can test that this works?

Sorry, already there. I will prepare a review.

**Comment by arunge** [comment]
@wahani as discussed, I now use a path variable, and I do not use `load(*.RData)` but `readRDS()` into a local variable.
I merge now.

**Pull request merged**
